# Shell variables
# Generated by 'wal'
wallpaper="/home/Kroni4/Pictures/wallpapers/ZQtHC817mOEO7sb.webp"

# Special
background='#111018'
foreground='#c3c3c5'
cursor='#c3c3c5'

# Colors
color0='#111018'
color1='#445A90'
color2='#5D6984'
color3='#6E748E'
color4='#897F98'
color5='#9C93AB'
color6='#CBB5BB'
color7='#c3c3c5'
color8='#5f5b6f'
color9='#445A90'
color10='#5D6984'
color11='#6E748E'
color12='#897F98'
color13='#9C93AB'
color14='#CBB5BB'
color15='#c3c3c5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
