--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/Kroni4/Pictures/wallpapers/ZQtHC817mOEO7sb.webp"

-- Special
background="#111018"
foreground="#c3c3c5"
cursor="#c3c3c5"

-- Colors
color0="#111018"
color1="#445A90"
color2="#5D6984"
color3="#6E748E"
color4="#897F98"
color5="#9C93AB"
color6="#CBB5BB"
color7="#c3c3c5"
color8="#5f5b6f"
color9="#445A90"
color10="#5D6984"
color11="#6E748E"
color12="#897F98"
color13="#9C93AB"
color14="#CBB5BB"
color15="#c3c3c5"
